version: Dev-ci{build}
skip_tags: true
shallow_clone: true
clone_folder: c:\projects\AutoUpdater.NET
init:
- ps: >-
    if ($env:appveyor_repo_tag -eq "true") { Exit-AppveyorBuild }


    $env:my_package_name = "AutoUpdater.NET.SelfDriven"


    $env:build_2_release = "false"

    $env:my_build_version = "v99.9.9-ci$env:appveyor_build_number"

    $env:my_package_version = "99.9.9.$env:appveyor_build_number"

    $env:my_release_version = "99.9.9.$env:appveyor_build_number"

    $env:is_prerelease = "false"


    if ($env:appveyor_repo_commit_message -match "\[v(?<ver>\d+.\d+.\d+)(?<meta>-?.*?)]")

    {
      $env:build_2_release = "true"
      $env:my_build_version = "v$($Matches.ver)$($Matches.meta)"
      $env:my_package_version = "$($Matches.ver)$($Matches.meta)"
      $env:my_release_version = "$($Matches.ver).$env:appveyor_build_number"
      Update-AppveyorBuild -Version "$env:my_build_version-ci$env:appveyor_build_number"

      if (-not ([string]::IsNullOrWhitespace($Matches.meta))) { $env:is_prerelease = "true" }
    }
assembly_info:
  patch: true
  file: '**\AutoUpdater.NET\Properties\AssemblyInfo.*'
  assembly_version: $(my_release_version)
  assembly_file_version: $(my_release_version)
  assembly_informational_version: $(my_package_version) #$(my_release_version)
environment:
  my_secret:
    secure: KyQ4Y+q48GXGJ1/dlnIm62Xz0oUwTcviRMrl02OiNGtin2DvVYMA27FbWfR5Xkx4
build_script:
- cmd: >-
    nuget install secure-file -ExcludeVersion

    nuget restore

    secure-file\tools\secure-file -decrypt c:\projects\AutoUpdater.NET\ZipExtractor\ZipExtractor.snk.enc -secret %my_secret%

    secure-file\tools\secure-file -decrypt c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.NET.snk.enc -secret %my_secret%

    secure-file\tools\secure-file -decrypt c:\projects\AutoUpdater.NET\UnitTests\UnitTests.snk.enc -secret %my_secret%

    msbuild "c:\projects\AutoUpdater.NET\ZipExtractor\ZipExtractor.csproj" /p:Configuration=Release /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild "c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.NET.csproj" /p:Configuration=Release /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


    msbuild "c:\projects\AutoUpdater.NET\ZipExtractor\ZipExtractor.csproj" /p:Configuration=Release-NET35 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild "c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.NET.csproj" /p:Configuration=Release-NET35 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


    msbuild "c:\projects\AutoUpdater.NET\ZipExtractor\ZipExtractor.csproj" /p:Configuration=Release-NET40 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild "c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.NET.csproj" /p:Configuration=Release-NET40 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


    msbuild "c:\projects\AutoUpdater.NET\ZipExtractor\ZipExtractor.csproj" /p:Configuration=Release-NET452 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild "c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.NET.csproj" /p:Configuration=Release-NET452 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


    msbuild "c:\projects\AutoUpdater.NET\ZipExtractor\ZipExtractor.csproj" /p:Configuration=Release-NET462 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild "c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.NET.csproj" /p:Configuration=Release-NET462 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


    nuget pack "c:\projects\AutoUpdater.NET\AutoUpdater.NET\build\Autoupdater.NET.SelfDriven.nuspec" -Version %my_package_version%


    7z a %my_package_name%-%my_build_version%.zip %APPVEYOR_BUILD_FOLDER%\AutoUpdater.NET\build\lib\*
artifacts:
- path: '%my_package_name%-%my_build_version%.zip'
- path: '%my_package_name%.%my_package_version%.nupkg'
before_deploy:
- ps: >-
    if ($env:appveyor_repo_tag -eq "true") { Exit-AppveyorBuild }

    if ($env:build_2_release -eq "false") { Exit-AppveyorBuild }
deploy:
- provider: NuGet
  api_key:
    secure: e7rKkhnUE1sgcI6NxGDdBOUi8+63vFjw1gNn4g0UZZYO4Uum78CzpkECN3qH6VI1
  skip_symbols: true
  artifact: '%my_package_name%.%my_package_version%.nupkg'
- provider: GitHub
  release: '$(my_build_version)'
  auth_token:
    secure: /GyKxy/BoEv0aU75gh8Y4G/QY7L3AnjvS6hezGUrQuqRC+i7yVS1G657HAWcv5xE
  artifact: '%my_package_name%-%my_build_version%.zip'
  on:
    is_prerelease: false
- provider: GitHub
  release: '$(my_build_version)'
  auth_token:
    secure: /GyKxy/BoEv0aU75gh8Y4G/QY7L3AnjvS6hezGUrQuqRC+i7yVS1G657HAWcv5xE
  artifact: '%my_package_name%-%my_build_version%.zip'
  prerelease: true
  on:
    is_prerelease: true